name: Node.js CI

on:
  push:
    branches: [ main, CI ]
  pull_request:
    branches: [ main, CI ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci -w app\expressjs-backend
      - run: npm test
      - run: npm ci -w app\react-frontend
      - run: npm run dev -w app\expressjs-backend
      - run: npm start -w app\react-frontend


